netd: Reset to known good config
Condor refuses to boot with the last few commits.Something seems to be broken.

01-01 01:50:21.410 1025 1497 E NetdConnector:
Communications error: java.io.IOException: No such
file or directory

Revert "SoftapController: support for Fast Session
Transfer" 01-01 01:50:21.412 1025 1497 E
NetdConnector: Error in NativeDaemonConnector:
java.io.IOException: No such file or directory This
reverts commit
cfa3aa941bb4eaf66d514a6014ffe2c9b4403f7e.

*This revert fixes boot.

Revert "server: Add custom implementation for tethering and statistics"

This reverts commit 6ca0ec59b56c62cc017fdb9ccde1059114e67f1f.

Revert "wlan: Add softap support through ndc commands."

This reverts commit 2c61b49cd59e42533d40c44e73b198e746351dfb.

Revert "SOFTAP: Notificate the STA (dis)connect message"

This reverts commit b18f24212cbf82aa2f96f2c85f3bf5d23e53fa20.

Revert "netd: Add support for IPv6 Tethering"

This reverts commit 5ac474ecf9404ade0a1d47455673f087b2d7d180.

Change-Id: I11770df885cf9776f9d2081fa942d6f1d76525e6